import 'jquery';
import '../scss/main.scss';
import '../pug/index.pug';
import './vendor/like-dislike'
import './vendor/rateBtn'
import './vendor/slider'
import './vendor/sliderTuchPunch'
import './vendor/jquery.simplePagination'
//import '../pug/page.pug';