import 'jquery';
import '../scss/main.scss';
import '../pug/index.pug';
import '../blocks/likeButton/like-dislike'
import '../blocks/rateBtn/rateBtn'
import '../blocks/slider/slider'
import '../blocks/slider/sliderTuchPunch'
import '../blocks/simplePagination/jquery.simplePagination'
import '../blocks/dropdown/handleCounter'
import '../blocks/dropdown/dropdown'
//import '../pug/page.pug';